name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  merge_group:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: mypy
        run: uv run mypy .

  ruff:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: ruff
        run: uv run ruff check --output-format=github .

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: .python-version

      - run: brew install libmagic
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Print help text
        uses: nick-fields/retry@v3.0.1
        with:
          timeout_seconds: 30
          max_attempts: 10
          on_retry_command: uv venv
          command: uv run python -m langchain_user_authn --help
